name: Build and Deploy

on:
  push:
    branches:
      - master  # Cambia "main" por el nombre de tu rama principal si es diferente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    # Puedes agregar pasos adicionales aquí según tus necesidades
